  - name: Install postgres development tools
    apt: 
      name: ['git', 'build-essential', 'cmake', 'valgrind']
      update_cache: true
      state: present

  - name: Install PostgreSQL apt key
    apt_key:
      url: https://www.postgresql.org/media/keys/ACCC4CF8.asc 
      state: present

  - name: Add PostgreSQL repository
    apt_repository:
      repo: "deb http://apt.postgresql.org/pub/repos/apt bullseye-pgdg main"
      state: present
      update_cache: true

  - name: Install PostgreSQL 12
    apt: 
      name: ['postgresql-12', 'postgresql-server-dev-12', 'pg-bsd-indent', 'perltidy', 'postgresql-12-dbgsym']
      update_cache: true
      state: present 


  - name: Make sure 'wheel' group exists
    group:
       name: wheel
       state: present

  - name: Allow 'wheel' group to have passwordless sudo
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%wheel'
      line: '%wheel ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'

  - name: Add work worker
    ansible.builtin.user:
      name: '{{ username }}'
      shell: /bin/bash
      state: present
      createhome: yes
      groups: wheel
      append: yes

  - name: Copy vim config
    ansible.builtin.copy:
      remote_src: yes
      src: /root/.vimrc
      dest: '/home/{{ username }}/.vimrc'
      owner: jan
      group: jan

  - name: Create ssh dir for work user
    ansible.builtin.file:
      path: '/home/{{ username }}/.ssh'
      state: directory
      mode: '0755'
      owner: jan
      group: jan

  - name: Copy ssh key
    ansible.builtin.copy:
      remote_src: yes
      src: /root/.ssh/authorized_keys
      dest: '/home/{{ username }}/.ssh/authorized_keys'
      owner: '{{ username }}'
      group: '{{ username }}'
      mode: '0600'

  - name: Checkout PostgreSQL
    git:
     repo: https://github.com/postgres/postgres.git
     dest: /home/{{ username }}/postgres
     update: no
     version: master
 
  - name: Download pgindent typedef
    get_url:
       url: https://buildfarm.postgresql.org/cgi-bin/typedefs.pl
       dest: '/home/{{ username }}/postgres/src/tools/pgindent/typedefs.list'

  - name: Update owner
    ansible.builtin.file:
      path: "/home/{{username}}/postgres"
      state: directory
      recurse: yes
      owner: '{{ username }}'
      group: '{{ username }}'

